### ISSUE TITLE
waveglow as vocoder

### ISSUE THREAD

**Issue by vikrantsharma7** [BogiHsu/Tacotron2-PyTorch#1]
Can I use waveglow, particularly the pretrained one from https://github.com/NVIDIA/waveglow for inference?
Or are some changes required?

Thanks

**Comment by BogiHsu** [comment]
> Can I use waveglow, particularly the pretrained one from https://github.com/NVIDIA/waveglow for inference?
> Or are some changes required?
> 
> Thanks

I haven't tried yet. But I think it works if you set the process of generating mel-spectrogram in `audio.py` the same as that of Waveglow.
