### ISSUE TITLE
Does reduction factor > 1 work?

### ISSUE THREAD

**Issue by lee-bin** [BogiHsu/Tacotron2-PyTorch#2]
Have you tried the performance with reduction factor > 1? Do you have some samples?

**Comment by BogiHsu** [comment]
> Have you tried the performance with reduction factor > 1? Do you have some samples?

The current version of hparams.py is for reduction factor (denoted as n_frames_per_step in hparams.py) of 3. You can find some samples in results/.

**Comment by lee-bin** [comment]
Thanks. @BogiHsu 
How do you find out the performance of reduction factor > 1 or = 1, is = 1 much better than > 1 or almost the same?  Why do you choose 3, for training or inference speed or just because of limited GPU memory?

**Comment by BogiHsu** [comment]
> Thanks. @BogiHsu
> How do you find out the performance of reduction factor > 1 or = 1, is = 1 much better than > 1 or almost the same? Why do you choose 3, for training or inference speed or just because of limited GPU memory?

The reduction factor highly influences the training speed, while I only observe little blur in sound quality. I guess the quality would be ok if you have a pretrained vocoder.
By the way, 3 for the reduction factor is just a random pick. R = 2 for the MOS test in the original tacotron paper.

**Comment by lee-bin** [comment]
Thanks.
