### ISSUE TITLE
Good alignment but bad prosody

### ISSUE THREAD

**Issue by moonnee** [BogiHsu/Tacotron2-PyTorch#3]
Hi, thanks a lot for this repo.
I tried this code on blizard challenge 2011 data with wavernn as decoder. The alignment is quite good, but the pitch of synthesized speech is wierd and so does the duration. Sometimes, synthesized speech is faster than groud truth. I tried copy synthesis with wavernn decoder, the speech is quite good. I don't know why this happens. Could you give some advice? Attached please find the aligments, synthesized speech and groud truth samples.
Thanks in advance. 

[samples.zip](https://github.com/BogiHsu/Tacotron2-PyTorch/files/3660720/samples.zip)

**Comment by BogiHsu** [comment]
Since there is no module handling prosody or speaking rate in Tacotron 2, I think it's inevitable that the results are weird when training on highly expressive corpus like blizzard. Maybe you can try other corpora with a plain tone or using GST-Tacotron.
