### ISSUE TITLE
README duplicate instruction

### ISSUE THREAD

**Issue by Jargonautika** [BogiHsu/Tacotron2-PyTorch#5]
Hi. In README.md you suggest three ways to run the training: 

1. Standard with just train.py
2. Using pre-trained models
3. Using tensorboard

The instructions for 2. and 3. are identical. I think that you need to update suggestion 3. to show which arguments to apply to allow tensorboard usage.

**Comment by BogiHsu** [comment]
I've updated README.md. Thanks a lot.
