### ISSUE TITLE
WaveGlow scaling

### ISSUE THREAD

**Issue by Jargonautika** [BogiHsu/Tacotron2-PyTorch#6]
Hi! This is not really an issue, but I've got a question about the tensors mel_outputs and mel_outputs_postnet in the save_mel() function in inference.py. 

When running inference I get a tensor of shape [(1, 80, 253)], for example. When I pass this tensor along to my working WaveGlow model ([from this project](https://github.com/NVIDIA/waveglow)), it takes the mel spectrograms and converts them to audio, but it's just static. 

The provided mel tensors from the WaveGlow people have differently scaled magnitude values. Here is a description of a sample vector from one of their mel tensors: 

DescribeResult(nobs=760, minmax=(-9.1658077, -4.7563148), mean=-6.8498592, variance=0.56033307, skewness=-0.34983542561531067, kurtosis=-0.3708913831845826)

Here is a description of a sample vector from one of your mel tensors after I've run inference: 

DescribeResult(nobs=282, minmax=(0.042787716, 0.4756053), mean=0.22464047, variance=0.0148157105, skewness=0.2994621992111206, kurtosis=-0.9376598291505811)

The number of nobs correlates to the number of milliseconds (I think?) so it shouldn't matter how many there are. The scale for the minmax tuple is off. Have you thought about how to scale this so that the two networks could work together? Any input you can provide would be very helpful.

**Comment by Jargonautika** [comment]
![Tacotron PKL Output Visualization](https://user-images.githubusercontent.com/31375780/69383570-9c3f5e80-0c7f-11ea-8223-c97c9084e640.png)

![WaveGlow PT Input Visualization](https://user-images.githubusercontent.com/31375780/69383578-a1041280-0c7f-11ea-92c1-2e4ce7818aef.png)

**Comment by Jargonautika** [comment]
They both look like real spectrograms to me, and the sizing is right, but that scale is odd.

**Comment by BogiHsu** [comment]
I think a better way to apply vocoders is directly modifying audio.py, making the feature extracting methods consistent. It's not easy to get good speech quality by simply scaling the generated spectrograms and passing them to vocoders.
